import assert from 'node:assert/strict';
import { terminalReceipt } from './lib/recovery.js';
let seq = 0;
const event = (type, data) => ({ seq: seq++, type, data });
const message = { id: 'input-1', source: { messageId: 'receipt-1' } };
const receipt = [{ id: 'receipt-1', status: 'accepted' }];
const input = event('agent/inbox/spliced', { target: 'next-turn', start: 0, inserted: [message] });
const start = event('turn/start', { turn: 1 });
const claim = event('agent/inbox/spliced', { target: 'next-turn', start: 0, removedCount: 1, inserted: [] });
const user = event('user/message', message);
const step = event('step/start', { turn: 1, step: 1 });
const end = event('turn/end', { turn: 1, reason: { kind: 'completed' } });
const completed = [input, start, claim, user, step, end];
assert.equal(terminalReceipt(completed, 0, receipt)?.stopReason, 'completed');
assert.equal(terminalReceipt(completed, completed.length, receipt), null, 'inherited completion never settles own work');
assert.equal(terminalReceipt(completed, 0, [{ id: 'missing', status: 'accepted' }]), null);
assert.equal(terminalReceipt(completed, 0, [{ id: 'receipt-1', status: 'queued' }]), null);
assert.equal(terminalReceipt([input, start, claim, user, end], 0, receipt), null, 'no-op completed turn did not execute its input');
const blocked = { ...end, data: { turn: 1, reason: { kind: 'blocked' } } };
assert.equal(terminalReceipt([input, start, claim, user, blocked], 0, receipt)?.stopReason, 'blocked', 'pre-step refusal accounts for claimed input');
assert.equal(terminalReceipt([input, start, claim, user, step], 0, receipt), null, 'open turn remains occupied');
const next = event('agent/inbox/spliced', { target: 'next-turn', start: 0, inserted: [{ id: 'input-2' }] });
const dropped = event('agent/inbox/spliced', { target: 'next-turn', start: 0, removedCount: 1, inserted: [], outcome: 'canceled' });
assert.equal(terminalReceipt([...completed, next], 0, receipt), null, 'pending inbox remains occupied');
assert.equal(terminalReceipt([...completed, next, dropped], 0, receipt), null, 'unrun canceled input cannot reuse an earlier completion');
console.log('native consumed-work recovery: receipts, queue, fork suffix, no-op, open/blocked turn and unrun cancellation passed');
